Repository AnoshMalik/arya-toot, pull requests merged in 2023-05, with the labels that each got.

#58 Feature/Database-Connection
  client/src/Components/MainContent.js
  client/src/pages/Home.js
  server/api.js
Labels: enhancement

#68 Added_cypress_tests_to_project
  client/src/Components/Header.js
  client/src/Components/LandingContent.js
  cypress.config.js
  cypress/.eslintrc.json
  cypress/e2e/landing.spec.cy.js
  cypress/fixtures/example.json
  cypress/screenshots/landing.spec.cy.js/landing page -- logins via github (failed).png
  cypress/support/commands.js
  cypress/support/e2e.js
  cypress/videos/landing.spec.cy.js.mp4
  package-lock.json
  package.json
  server/api.js
  server/app.js
Labels: enhancement

#69 Feature/update styling
  client/src/Components/Footer.js
  client/src/Components/Header.js
  client/src/Components/LandingContent.js
  client/src/Components/MainContent.js
  client/src/Components/ProfileIcon.js
  client/src/index.html
  client/src/pages/History.js
  cypress/e2e/landing.spec.cy.js
  server/api.js
Labels: bug, enhancement

#72 Feature/login to db
  client/src/Components/ProfileIcon.js
  db/db-config.js
  knexfile.js
  server/api.js
  server/passport.js
Labels: enhancement

#73 Corrected history page not loading bug
  client/src/Components/MainContent.js
  client/src/pages/History.js
  server/api.js
Labels: bugfix

#74 Feature/about page
  client/src/assets/T-shirt.png
  client/src/pages/About.js
Labels: enhancement
